---
version: '3'

services:
#1. https://github.com/timkolotov/3proxy-docker
  3proxy:
    build: ./applications/3proxy
    container_name: 3proxy
    restart: always
    environment:
      - HTTP_PORT=10301
      - SOCKS_PORT=10302
      - USER=chinastrong
      - PASS=strong66uu77
    volumes:
       - ./applications/3proxy/passwd:/etc/3proxy/passwd:ro
    ports:
      - "1080:1080"
      - "8080:8080"
#2. https://github.com/linuxserver/docker-wireguard
  wireguard:
    build: ./applications/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=5.42.77.197
      - SERVERPORT=10401
      - PEERS=10 #Number of peers to create confs for. Required for server mode. Can also be a list of names: myPC,myPhone,myTablet (alphanumeric only)
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 10401:10401/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
