version: '3'

services:
#1. https://github.com/timkolotov/3proxy-docker
  3proxy:
    build: ./applications/3proxy
    container_name: 3proxy
    restart: always
    environment:
      - HTTP_PORT=10301
      - SOCKS_PORT=10302
      - USER=chinastrong
      - PASS=strong66uu77
    volumes:
       - ./applications/3proxy/passwd:/etc/3proxy/passwd:ro
    ports:
      - "1080:1080"
      - "8080:8080"

