---
version: '3'

services:
#1. https://github.com/timkolotov/3proxy-docker
  3proxy:
    build: ./applications/3proxy
    container_name: 3proxy
    restart: always
    environment:
      - HTTP_PORT=10301
      - SOCKS_PORT=10302
      - USER=chinastrong
      - PASS=strong66uu77
    volumes:
       - ./applications/3proxy/passwd:/etc/3proxy/passwd:ro
    ports:
      - "1080:1080"
      - "8080:8080"
#2. https://github.com/felixfischer/wireguard-docker
  wireguard:
    build: ./applications/wireguard/
    container_name: wireguard
    cap_add:
     - NET_ADMIN
    sysctls:
     - net.ipv4.ip_forward=1
    volumes:
       - ./applications/wireguard/configs:/etc/wireguard
    devices:
       - "/dev/net/tun:/dev/net/tun"
    ports:
     - 10401:10401/udp
    # Uncomment the following line when 'AllowedIPs' is '0.0.0.0/0'
    # privileged: true
    restart: always