kind: pipeline
type: docker
name: Docker image build

trigger:
  branch:
    - master
    
steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quackerd/d2ray